version: "3"

services:
  db:
    image: mysql:8.0.20
    container_name: db-notebook
    restart: always
    networks:
      - default
      - habanero-network
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/ddl:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=api-notebook
      - MYSQL_USER=api
      - MYSQL_PASSWORD=abc
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Tokyo
    ports:
      - 3306:3306

  api:
    image: api-notebook:latest
    container_name: api-notebook
    restart: always
    networks:
      - default
      - habanero-network
    ports:
      - 8082:80

networks:
  habanero-network:
    external: true